---
http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: ${ELASTICSEARCH_HOST_PORT}

## X-Pack security credentials
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.username: ${ELASTIC_USERNAME}
xpack.monitoring.elasticsearch.password: ${ELASTIC_PASSWORD}